http://windowsupdate.microsoft.com
http://*.windowsupdate.microsoft.com
https://*.windowsupdate.microsoft.com
http://*.update.microsoft.com
https://*.update.microsoft.com
http://*.windowsupdate.com
http://download.windowsupdate.com
https://download.microsoft.com
http://*.download.windowsupdate.com
http://wustat.windows.com
http://ntservicepack.microsoft.com
http://go.microsoft.com
http://dl.delivery.mp.microsoft.com
https://dl.delivery.mp.microsoft.com
http://*.delivery.mp.microsoft.com
https://*.delivery.mp.microsoft.com
https://*.cluster.b.redcloak.secureworks.com
http://*.cluster.b.redcloak.secureworks.com
https://cluster.b.redcloak.secureworks.com
http://cluster.b.redcloak.secureworks.com
https://secure.xravelsoft.com
https://www.secure.xravelsoft.com
https://*.google.com
https://*.gstatic.com
https://*.googleusercontent.com